### ISSUE TITLE
Cannot connect with account. OAuth Error

### ISSUE THREAD

**Issue by aproposnix** [concentricsky/android-viewer-for-khan-academy#2]
On my device (HTC One V) I cannot connect to my Khan account. Whenever I try to sign in I only see the message "OAuth Error. Invalid Consumer".

**Comment by JGjorgji** [comment]
I also have this issue, Nexus 7 running CM10.2.

**Comment by CharString** [comment]
It does show a little throbber before the error message. But that could be just an animation.

**Comment by ghost** [comment]
It would be very nice if you could fix this :-)

**Comment by lbyers** [comment]
Just reading the README says this:

"Without a valid API key, most of the app will still run fine. When trying to log in, though, you'll be presented with a blank page and the text "OAuth error. Invalid consumer." To use user login features, register at https://www.khanacademy.org/api-apps/register and enter the appropriate values into oauth_credentials.json."

Hopefully that helps.

**Comment by Freso** [comment]
If the app needs the user to enter additional credentials, it should probably set last provide UI for this. 

Until then, where is the oauth_credentials.json that the data should go into and what is the schema of it?
